baseURL: "https://larryhui7.github.io"
title: Larry Hui
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
  tag: tags

menu:
  main:
    - name: Books
      url: books/
      weight: 5
    - name: Papers
      url: papers/
      weight: 2
    - name: Courses
      url: courses/
      weight: 3
    - name: Data
      url: data/
      weight: 4
    - name: Blog
      url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
      weight: 6

params:
  description: "This website hosts Larry Hui's research papers, books, course materials, data, curriculum vitae, and contact information."
  author: Larry Hui
  # googleAnalyticsID: "G-XXXXX"
  DateFormat: "January 2006"
  defaultTheme: light
  hideFooter: false
  disableThemeToggle: true
  ShowShareButtons: false
  ShowReadingTime: false
  disableSpecial1stPost: true
  disableAnchoredHeadings: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowAllPagesInArchive: false
  MainSections: ["books", "courses", "papers", "data"]
  ShowToc: false
  disableScrollToTop: true
  TocOpen: true
  ShowWordCount: false
  UseHugoToc: true
  comments: false
  math: true
  profileMode:
    enabled: true
    title: Hey! I'm Larry Hui
    subtitle: |
      Welcome to my page! I am a rising senior at <a href="https://www.berkeley.edu/" style="color:#3399ff;">UC Berkeley</a>, studying <a href="https://www.me.berkeley.edu/" style="color:#3399ff;">Mechanical Engineering</a> and <a href="https://www.berkeley.edu/" style="color:#3399ff;">EECS</a>. Have some fun exploring my page to see some projects, classes, and research I've been involved in! Feel free to contact me as well!<br><br>

      Currently, I am a lead TA for Dynamic Systems and Feedback Controls. This past semester I took electives in Machine Learning, Convex Optimization, The Finite Element Method, Convective Transport and Computational Methods. My interests span multiple areas, namely FEA, optimal control and linear system theory, optimization, and machine learning as they relate to robotics.<br><br>

      I have experience working in a small group at a startup, working as a Hardware Engineering intern assisting by creating and tolerancing a drone-based hodoscope. I spent time integrating the PCB design into the enclosure, writing code for failure analysis, and researching deployment methods. Currently, I am doing research with Professor Grace X. Gu on implementing MGNs and PINNs in MATLAB. We are also reviewing differentiable GNN-based PDE solvers as they relate to fluid-solid interactions.<br><br>

      Besides academics, I enjoy cooking, trying cocktails, exploring restaurants around the world, and travelling (I literally spawn randomly around the world...). I consider myself a classical music afficionado with my favourite pieces being: Rachmaninoff Piano Conerto 2, Mahler Symphony 2, Schubert Piano Sonata No. 19; sometimes I play the trumpet, and all the other brass instruments. I also love to fly. I have my private pilot's licence, a high performance, and complex aircraft endorsements. I am working on my instrument rating. Patience. <br><br>

      Have some fun exploring my page to see some projects, classes, and research I've been involved in! Feel free to contact me as well!<br><br>

      <div id="fun-fact">Fun fact: This sentence changes every time you reload!</div>

      <script>
        const facts = [
          "Fun fact: My favorite Wii game is <strong>Lego Star Wars: The Complete Saga</strong>.",
          "Fun fact: My shell of choice is <strong>zsh</strong>.",
          "Fun fact: My favorite TV show is <strong>The Sopranos</strong>.",
          "Fun fact: I once built a drone-based hodoscope.",
          "Fun fact: I have a private pilot's license."
        ];
        const randomFact = facts[Math.floor(Math.random() * facts.length)];
        document.getElementById("fun-fact").innerHTML = randomFact;
      </script>
    imageUrl: "LarryProfilePic.png"
    imageWidth: 155
    imageHeight: 160
    buttons:
      - name: Papers
        url: papers/
      - name: Data
        url: data/
      - name: Books
        url: books/
      - name: Courses
        url: courses/
      - name: Tags
        url: tags/
      - name: Archive
        url: archive/
      - name: Blog
        url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

  socialIcons:
    - name: CV
      url: cv.pdf
    - name: Email
      url: mailto:larryhui7@berkeley.edu
    - name: Location
      url: location/
    - name: linkedin
      url: https://www.linkedin.com/in/larryhui7/
    - name: GitHub
      url: https://github.com/larryhui7
    - name: kaggle
      url: https://www.kaggle.com/larryhui7
    - name: spotify
      url: https://open.spotify.com/user/larryhui7
    - name: Threads
      url:

  assets:
    disableScrollBarStyle: true
  cover:
    hiddenInList: false
    hiddenInSingle: true
  label:
    text: "Larry Hui"
    icon: favicon.ico
    iconHeight: 18

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    guessSyntax: true
    style: autumn
  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 2
