"""Voronoi geometry and integrals inside a convex polygon Q. Only NumPy is required.

Everything the demos need from Sec. II of the paper is here:

    voronoi / cell      Voronoi partition of Q generated by the agents
    stats / all_stats   mass M_V, centroid C_V, cost H and gradient dH/dp_i of each cell
    log_density         the density functions phi(q), including the Sec. V-B formations
    sensing_trace       Table I, "Adjust sensing radius"
    monitor_update      Table II, "Monitoring"

Polygons are (k, 2) arrays of vertices in counter-clockwise order. Positions
are an (n, 2) array with one row per agent.

Uniform-density integrals use the exact polygon formulas. Other densities use
Gauss quadrature on a triangle fan; see METHODS.md.
"""
from functools import lru_cache
import numpy as np


# ---------------------------------------------------------------------------
# Voronoi cells
# ---------------------------------------------------------------------------

def clip(poly, normal, bound, tol=1e-11):
    """Cut a convex polygon with a half-plane.

    Input:  poly (k, 2) CCW vertices; the half-plane is normal @ x <= bound.
    Output: vertices of the part of poly inside the half-plane (may be empty).
    """
    poly = np.asarray(poly, float)
    if len(poly) == 0:
        return np.empty((0, 2))
    out = []
    a = poly[-1]
    da = np.dot(normal, a) - bound
    for b in poly:
        db = np.dot(normal, b) - bound
        if (da <= tol) != (db <= tol):
            # The edge a-b crosses the boundary: keep the crossing point.
            out.append(a + da / (da - db) * (b - a))
        if db <= tol:
            out.append(b)
        a, da = b, db
    if not out:
        return np.empty((0, 2))
    out = np.asarray(out)
    # Drop repeated vertices.
    return out[np.linalg.norm(out - np.roll(out, 1, axis=0), axis=1) > 1e-10]


def cell(domain, positions, i, indices=None):
    """Voronoi cell of agent i inside the domain.

    Start from Q and cut it with the perpendicular bisector between agent i and
    each other agent j. The points closer to p_i than p_j satisfy
    2 (p_j - p_i) . q <= |p_j|^2 - |p_i|^2.

    Input:  domain (k, 2); positions (n, 2); i; indices = the agents j to use
            (default all). Passing only the agents i has detected gives the
            local cell used by the distributed algorithms.
    Output: (m, 2) vertices of the cell.
    """
    v = np.asarray(domain, float).copy()
    pi = positions[i]
    for j in (range(len(positions)) if indices is None else indices):
        if j == i:
            continue
        d = positions[j] - pi
        if np.dot(d, d) < 1e-20:
            raise ValueError("Coincident agents have ambiguous cells; separate them.")
        v = clip(v, 2*d, np.dot(positions[j], positions[j]) - np.dot(pi, pi))
    return v


def voronoi(domain, positions):
    """All Voronoi cells: a list with one vertex array per agent."""
    return [cell(domain, positions, i) for i in range(len(positions))]


def inside(points, domain, tol=1e-9):
    """Boolean array: which of the points lie inside the convex CCW domain."""
    points = np.atleast_2d(points)
    a = np.asarray(domain)
    e = np.roll(a, -1, axis=0) - a
    d = points[:, None, :] - a[None, :, :]
    # A point is inside when it is to the left of every edge.
    return np.all(e[None, :, 0]*d[:, :, 1] - e[None, :, 1]*d[:, :, 0] >= -tol, axis=1)


def neighbors(cells, positions):
    """Voronoi neighbors of every agent.

    Two agents are neighbors when their cells share an edge of positive length
    (touching at a single vertex does not count).

    Output: list of sorted index lists, one per agent.
    """
    answer = []
    for i, poly in enumerate(cells):
        found = set()
        dif = positions - positions[i]
        bound = np.sum(positions**2, axis=1) - np.dot(positions[i], positions[i])
        for a, b in zip(poly, np.roll(poly, -1, axis=0)):
            if np.linalg.norm(a - b) < 1e-7:
                continue
            # Agent j is a neighbor if both ends of this edge are on the i-j bisector.
            mask = (np.abs(2*dif@a - bound) < 2e-7) & (np.abs(2*dif@b - bound) < 2e-7)
            found.update(np.where(mask)[0].tolist())
        found.discard(i)
        answer.append(sorted(found))
    return answer


# ---------------------------------------------------------------------------
# Integrals over a cell: mass, centroid, cost, gradient
# ---------------------------------------------------------------------------

def polygon_moments(poly):
    """Exact area integrals of a polygon (the uniform-density case).

    Output: (area, first, second) where first = integral of q and
            second = integral of q q^T over the polygon.
    """
    if len(poly) < 3:
        raise ValueError("A cell has zero area. Reset with distinct interior agents.")
    x, y = np.asarray(poly).T
    X, Y = np.roll(x, -1), np.roll(y, -1)
    c = x*Y - X*y
    area = c.sum()/2
    if area <= 1e-16:
        raise ValueError("A cell is numerically degenerate.")
    first = np.array([np.sum((x + X)*c), np.sum((y + Y)*c)])/6
    xx = np.sum((x*x + x*X + X*X)*c)/12
    yy = np.sum((y*y + y*Y + Y*Y)*c)/12
    xy = np.sum((2*x*y + x*Y + X*y + 2*X*Y)*c)/24
    return area, first, np.array([[xx, xy], [xy, yy]])


@lru_cache(maxsize=8)
def rule(order):
    """Gauss-Legendre points and weights on the reference triangle (Duffy map)."""
    z, w = np.polynomial.legendre.leggauss(order)
    z, w = (z + 1)/2, w/2
    u, v = np.meshgrid(z, z, indexing="ij")
    wu, wv = np.meshgrid(w, w, indexing="ij")
    return u.ravel(), v.ravel(), (wu*wv*(1 - u)).ravel()


def quadrature(poly, edge=.35, order=5):
    """Quadrature points and weights for integrating over a convex polygon.

    The polygon is split into a fan of triangles around its vertex average, and
    triangles are bisected until no side is longer than `edge`.

    Output: q (m, 2) points and w (m,) weights, so that
            integral of f over poly ~= sum(w * f(q)).
    """
    center = np.mean(poly, axis=0)
    tris = np.stack([np.repeat(center[None, :], len(poly), axis=0), poly,
                     np.roll(poly, -1, axis=0)], axis=1)
    ready = []
    for _ in range(14):
        lengths = np.stack([np.sum((tris[:, 1] - tris[:, 0])**2, axis=1),
                            np.sum((tris[:, 2] - tris[:, 1])**2, axis=1),
                            np.sum((tris[:, 0] - tris[:, 2])**2, axis=1)], axis=1)
        split = lengths.max(axis=1) > edge**2
        if np.any(~split):
            ready.append(tris[~split])
        if not np.any(split):
            break
        # Bisect the longest side of every triangle that is still too large.
        t = tris[split]
        j = lengths[split].argmax(axis=1)
        rows = np.arange(len(t))
        a, b, c = t[rows, j], t[rows, (j + 1) % 3], t[rows, (j + 2) % 3]
        mid = (a + b)/2
        tris = np.concatenate([np.stack([a, mid, c], axis=1), np.stack([mid, b, c], axis=1)])
    else:
        ready.append(tris)
    t = np.concatenate(ready)
    a, b, c = t[:, 0], t[:, 1], t[:, 2]
    u, v, w = rule(order)
    q = (a[:, None, :] + u[None, :, None]*(b - a)[:, None, :]
         + ((1 - u)*v)[None, :, None]*(c - a)[:, None, :])
    det = np.abs((b - a)[:, 0]*(c - a)[:, 1] - (b - a)[:, 1]*(c - a)[:, 0])
    return q.reshape(-1, 2), (det[:, None]*w[None, :]).ravel()


def log_density(q, cfg):
    """log phi(q) for the density selected in cfg['density'].

    uniform    phi = 1
    gaussian   phi = exp(-beta |q - (xc, yc)|^2)                (Fig. 3)
    ellipse    phi = exp(-kappa g^2),  g = a x^2 + b y^2 - r^2  (Sec. V-B, Fig. 7)
    disk       phi = exp(-kappa SR_l(g)), SR_l the smooth ramp  (Sec. V-B, Fig. 8)
    line       phi = exp(-kappa (a x + b y + c)^2)              (Sec. V-B)

    Input:  q (..., 2) points; cfg the page configuration.
    Output: array of log phi with the leading shape of q. Working with logs
            keeps the sharp kappa = 500 densities from underflowing.
    """
    q = np.asarray(q)
    x, y = q[..., 0], q[..., 1]
    name = cfg['density']
    xc, yc = cfg.get('xc', 0), cfg.get('yc', 0)
    if name == 'uniform':
        return np.zeros_like(x)
    if name == 'gaussian':
        return -cfg['beta']*((x - xc)**2 + (y - yc)**2)
    if name == 'line':
        return -cfg['kappa']*(cfg['a']*x + cfg['b']*y + cfg['line_c'])**2
    g = cfg['a']*(x - xc)**2 + cfg['b']*(y - yc)**2 - cfg['r2']
    if name == 'ellipse':
        return -cfg['kappa']*g*g
    if name == 'disk':
        ramp = g*(np.arctan(cfg['ell']*g)/np.pi + .5)
        return -cfg['kappa']*ramp
    raise ValueError('Unknown density')


def stats(poly, p, cfg, scale=1.):
    """Mass, centroid, cost and gradient of one cell (Sec. II).

        M = integral_V phi dq
        C = (1/M) integral_V q phi dq
        H = integral_V |q - p|^2 phi dq
        dH/dp = 2 M (p - C)

    Input:  poly the cell, p the agent position, cfg the page configuration,
            scale a constant multiplying phi (used by Coverage behavior I).
    Output: (M, C, H, dH/dp).
    """
    area, first, second = polygon_moments(poly)
    if cfg['density'] == 'uniform':
        mass = area*scale
        centroid = first/area
        cost = scale*(np.trace(second) - 2*np.dot(p, first) + area*np.dot(p, p))
        return mass, centroid, max(0., cost), 2*mass*(p - centroid)
    # Non-uniform density: quadrature, finer for the sharp formation densities.
    level = int(cfg.get('accuracy', 1))
    order = (3, 5, 7)[level]
    edge = (.6, .4, .25)[level]
    if cfg['density'] in ('ellipse', 'disk', 'line'):
        edge = min(edge, (2.4, 1.7, 1.2)[level]/np.sqrt(cfg['kappa']))
        edge = max(edge, .035)
    q, w = quadrature(poly, edge=edge, order=order)
    logs = log_density(q, cfg)
    # Factor out the largest density value so tiny masses still give a centroid.
    shift = logs.max()
    weights = w*np.exp(logs - shift)
    denom = weights.sum()
    centroid = weights@q/denom
    factor = np.exp(shift)*scale
    mass = denom*factor
    d = p - q
    cost = factor*np.dot(weights, np.sum(d*d, axis=1))
    gradient = 2*factor*(weights@d)
    return mass, centroid, float(cost), gradient


def all_stats(domain, positions, cfg, scale=1.):
    """Voronoi partition plus the integrals of every cell.

    Output: (cells, masses (n,), centroids (n, 2), total cost H, gradients (n, 2)).
    """
    cells = voronoi(domain, positions)
    s = [stats(v, p, cfg, scale) for v, p in zip(cells, positions)]
    return (cells, np.array([v[0] for v in s]), np.array([v[1] for v in s]),
            float(sum(v[2] for v in s)), np.array([v[3] for v in s]))


# ---------------------------------------------------------------------------
# Distributed building blocks (Sec. IV)
# ---------------------------------------------------------------------------

def sensing_trace(domain, positions, i, radius):
    """Table I, "Adjust sensing radius" (Sec. IV-B, Fig. 4).

    Agent i finds its own Voronoi cell using only the agents it can detect:

        1. detect all agents within distance R
        2. W = Q  ∩  B(p_i, R)  ∩  half-planes of the detected agents
        3. if R >= 2 max_{q in W} |q - p_i|, W is the true Voronoi cell: stop
        4. otherwise double R and repeat

    Input:  domain, positions, agent index i, starting radius.
    Output: (cell, final_radius, trace). final_radius = 2 max |q - p_i| is the
            smallest radius that certifies the cell. trace has one dict per
            value of R tried, which the radius pages replay step by step.

    The disk B(p_i, R) is cut as a 64-sided polygon that contains it, so the
    test in step 3 can only be stricter than the paper's. Once it passes, W is
    inside B(p_i, R/2) and the disk no longer touches it.
    """
    R = max(float(radius), 1e-4)
    trace = []
    for _ in range(30):
        detected = np.where(np.linalg.norm(positions - positions[i], axis=1) <= R + 1e-10)[0]
        v = cell(domain, positions, i, detected)
        if np.linalg.norm(v - positions[i], axis=1).max() > R/2 + 1e-9:
            for angle in np.linspace(0, 2*np.pi, 64, endpoint=False):
                normal = np.array([np.cos(angle), np.sin(angle)])
                v = clip(v, normal, np.dot(normal, positions[i]) + R)
        reach = np.linalg.norm(v - positions[i], axis=1).max()
        certified = R >= 2*reach - 1e-9
        trace.append({'radius': R, 'reach': float(reach), 'required': float(2*reach),
                      'detected': detected.tolist(), 'cell': v, 'certified': bool(certified)})
        if certified:
            return v, 2*reach, trace
        R *= 2
    raise RuntimeError('Sensing radius did not certify')


def monitor_update(old, new, event=False):
    """Table II, "Monitoring" (Sec. IV-B).

    Each agent stores a weight for every other agent:
        3 = Voronoi neighbor that is moving, 1 = neighbor that is idle, 0 = not a neighbor.
    A jump of +2 or more means a neighbor started moving or a moving agent
    became a neighbor, so the agent's centroid may be out of date.

    Input:  old stored weights, new current weights, event = the current flag.
    Output: (stored, event, triggered). The stored weights are replaced by the
            new ones whenever any weight changed by 2 or more in either
            direction. event stays set until the controller clears it.
            triggered says whether this call raised it.
    """
    old, new = np.asarray(old), np.asarray(new)
    delta = new - old
    changed = bool(np.any(np.abs(delta) >= 2))
    triggered = bool(np.any(delta >= 2))
    return (new if changed else old).copy(), bool(event or triggered), triggered
